version: "3.7"
services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: flow
      MYSQL_USER: flow
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
