server:
    port: ${PORT}

spring:
  datasource:
    url: jdbc:mysql://db-fmmf5.pub-cdb.ntruss.com/flow?useSSL=false
    username: flow
    password: ${CLOUD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    user: flow
    password: ${CLOUD_DB_PASSWORD}
    url: jdbc:mysql://db-fmmf5.pub-cdb.ntruss.com/flow?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    baseline-on-migrate: true
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        event:
          merge:
            entity_copy_observer: allow
    database: mysql

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health